[package]
name = "unleash-edge-http-client"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
publish = true
license.workspace = true

[dependencies]
ahash = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
etag = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
lazy_static = { workspace = true }
p12-keystore = { workspace = true }
pkix = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
unleash-edge-cli = { workspace = true }
unleash-edge-types = { workspace = true }
unleash-types = { workspace = true }
unleash-yggdrasil = { workspace = true }
url = { workspace = true }

[dev-dependencies]
axum-test = { workspace = true }