[package]
name = "unleash-edge-enterprise"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
publish = true
license-file = "../../../LICENSE-ENTERPRISE.md"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
unleash-edge-cli = { workspace = true }
unleash-edge-http-client = { workspace = true }
unleash-edge-types = { workspace = true }
ulid = { workspace = true }
unleash-edge-persistence = { workspace = true }
