[package]
name = "unleash-edge-appstate"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
publish = true
license.workspace = true

[features]
enterprise = []

[dependencies]
axum = { workspace = true }
dashmap = { workspace = true }
ipnet = { workspace = true }
prometheus = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
unleash-edge-auth = { workspace = true }
unleash-edge-cli = { workspace = true }
unleash-edge-delta = { workspace = true }
unleash-edge-feature-cache = { workspace = true }
unleash-edge-feature-refresh = { workspace = true }
unleash-edge-http-client = { workspace = true }
unleash-edge-persistence = { workspace = true }
unleash-edge-streaming = { workspace = true }
unleash-edge-types = { workspace = true }
unleash-types = { workspace = true }
