[package]
name = "unleash-edge"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata.wix]
upgrade-guid = "ABA6D0AC-79E6-422A-8CC2-68D62D86AEDA"
path-guid = "92C33CAD-2C77-4B3F-BABC-861926D35EED"
license = false
eula = false

[features]
default = ["s3-persistence"]
s3-persistence = ["aws-sdk-s3", "aws-config"]
enterprise = ["unleash-edge-cli/enterprise"]

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
axum = { workspace = true }
axum-extra = { workspace = true }
axum-server = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap-markdown = { workspace = true }
dashmap = { workspace = true }
etag = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
ipnet = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true }
prometheus = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
socket2 = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ulid = { workspace = true }
unleash-edge-appstate = { workspace = true }
unleash-edge-auth = { workspace = true }
unleash-edge-backstage = { workspace = true }
unleash-edge-cli = { workspace = true }
unleash-edge-client-api = { workspace = true }
unleash-edge-delta = { workspace = true }
unleash-edge-edge-api = { workspace = true }
unleash-edge-enterprise = { workspace = true }
unleash-edge-enterprise-api = { workspace = true }
unleash-edge-feature-cache = { workspace = true }
unleash-edge-feature-refresh = { workspace = true }
unleash-edge-frontend-api = { workspace = true }
unleash-edge-http-client = { workspace = true }
unleash-edge-metrics = { workspace = true }
unleash-edge-offline = { workspace = true }
unleash-edge-persistence = { workspace = true }
unleash-edge-request-logger = { workspace = true }
unleash-edge-types = { workspace = true }
unleash-types = { workspace = true }
unleash-yggdrasil = { workspace = true }
url = { workspace = true }

[dev-dependencies]
axum-test = { workspace = true }
tracing-test = { workspace = true }
serde_json = { workspace = true }
